apiVersion:
kind: PersistentVolumeClaim
metadata:
  name: mysql-dados
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    request:
      storage: 10Gi
    storageClassName: standard-rwo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        -image: vitrezz/projeto-database:1.0
        args:
        - "--ignore-db-dir=lost+found"
        imagePullPolicy: Aways
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
         volumeMounts:
        - name: mysql-dados
          mouthPath: /var/lib/mysql/
      volumes:
      - name: mysql-dados
        persistentVolumeClaim:
          claimName: mysql-dados
---
apiVersion: app/v1
kind: Deployment
metada:
  name: php
  labels:
    app: php
spec:
  replicas: 6
  selector: 
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: vitrezz/projeto-backend:1.0
        imagePullPolicy: Aways
        ports:
        - containerPort: 80

